src/CadeMeuMedico/CadeMeuMedico/Models/Especialidade.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidade
    {
        public Especialidade()
        {
            this.Medicos = new HashSet<Medico>();
        }
    
        public int IDEspecialidade { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Medico> Medicos { get; set; }
    }
}

src/CadeMeuMedico/CadeMeuMedico/Controllers/EspecialidadesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CadeMeuMedico.Models;

namespace CadeMeuMedico.Controllers
{
    public class EspecialidadesController : BaseController
    {
        private EntidadesCadeMeuMedicoBD db = new EntidadesCadeMeuMedicoBD();

        public ActionResult Index()
        {
            var especialidades = db.Especialidades;
            return View(especialidades);
        }

        public ActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Adicionar(Especialidade especialidade)
        {
            if (ModelState.IsValid)
            {
                db.Especialidades.Add(especialidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(especialidade);
        }

        public ActionResult Editar(long id)
        {
            Especialidade especialidade = db.Especialidades.Find(id);

            return View(especialidade);
        }

        [HttpPost]
        public ActionResult Editar(Especialidade especialidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(especialidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(especialidade);
        }

        [HttpPost]
        public string Excluir(long id)
        {
            try
            {
                Especialidade especialidade = db.Especialidades.Find(id);
                db.Especialidades.Remove(especialidade);
                db.SaveChanges();
                return Boolean.TrueString;
            }
            catch
            {
                return Boolean.FalseString;
            }
        }
    }
}

src/CadeMeuMedico/CadeMeuMedico/Views/Especialidades/Adicionar.cshtml
@model CadeMeuMedico.Models.Especialidade

@{
    ViewBag.Title = "Adicionar";
}

<h2>Adicionar Especialidade</h2>

@using (Html.BeginForm("Adicionar", "Especialidades", FormMethod.Post, new{@class = "form-horizontal"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados da especialidade</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new{@class="form-control"})
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <br />
        <p>
            <input type="submit" value="Gravar" class="btn btn-primary" />
        </p>
    </fieldset>
}

@section Scripts {
    <script>
        $("#menuEspecialidades").addClass("active");
    </script>
}

src/CadeMeuMedico/CadeMeuMedico/Views/Especialidades/Editar.cshtml
@model CadeMeuMedico.Models.Especialidade

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Especialidade</h2>

@using (Html.BeginForm("Editar", "Especialidades", FormMethod.Post, new{@class = "form-horizontal"})) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Dados da especialidade</legend>
        @Html.HiddenFor(model => model.IDEspecialidade)
        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Nome, new{@class="form-control"})
            @Html.ValidationMessageFor(model => model.Nome)
        </div>
        <br />
        <p>
            <input type="submit" value="Gravar" class="btn btn-primary" />
        </p>
    </fieldset>
}

@section Scripts {
    <script>
        $("#menuEspecialidades").addClass("active");
    </script>
}

src/CadeMeuMedico/CadeMeuMedico/Views/Especialidades/Index.cshtml
@model IEnumerable<CadeMeuMedico.Models.Especialidade>

@{
    ViewBag.Title = "Especialidades";
}

<h2>Especialidades</h2>

<p>
    @Html.ActionLink("Adicionar nova especialidade", "Adicionar", null, new {@class = "btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.IDEspecialidade }) |
            @Html.ActionLink("Excluir", "Excluir", new { id=item.IDEspecialidade }, new {@class="excluir"})
        </td>
    </tr>
}

</table>

@section Scripts{
    <script>
        $(function () {
            var linhaAtual;
            
            $("#menuEspecialidades").addClass("active");

            $(".excluir").on("click", function () {
                if (confirm("Confirma a exclusão da especialidade?")) {
                    var urlExclusao = $(this).attr("href");
                    linhaAtual = $(this).closest("tr");

                    $.ajax({
                        url: urlExclusao,
                        type: "POST"
                    }).done(function (excluiu) {
                        if (excluiu) {
                            linhaAtual.remove();
                        } else {
                            alert("Ocorreu algum problema na exclusão da especialidade :(, verifique se algum médico possui essa especialidade.");
                        }
                    }).fail(function () {
                        alert("Ocorreu algum erro :(");
                    });
                }

                return false;
            });
        });

    </script>
}